#!/usr/bin/python3

import textwrap as tw
import sys
import os

def echo_help():
    print (
            tw.dedent(
            '''
                # Provide single vm file #
                Usage:   > ./VMtranslator file.vm
                Output:  file.asm

                # Or provide directory containing vm files #
                Usage:   > ./VMtranslator dir
                Output:  dir/file1.asm dir/file2.asm ...
            '''
            )
          )
    exit(1) # Exit with non-zero status

def get_files(arg):
    files = []
    if arg.endswith('.vm'):
        files.append(arg)
    elif os.path.isdir():
        for filename in os.listdir(arg):
            if filename.endswith('.vm'):
                files.append(filename)
    return files

if __name__ == '__main__':
    print ("[Python VMtranslator]")
    num_args = len(sys.argv)
    if num_args != 2:
        echo_help()         

    files_to_translate = get_files(sys.argv[1])
    if len(files_to_translate) == 0):
        echo_help()

    
